### ISSUE TITLE
Add support for Medium high speed

### ISSUE THREAD

**Issue by elitemike** [finity69x2/fan-control-entity-row#39]
Lutron Caseta fan switches support "low, medium, medium-high, high". Could this be added?

**Comment by finity69x2** [comment]
Unfortunately I've decided to limit the number of speeds that the plugin can support.

I've had requests for every number of speeds from 2 to 10. And I just can't keep up with the complexity of all of the possible iterations of the different speeds.

At a certain point the names of the speeds get crazy. low-med-high is fairly straight forward. as is low-high so I added that option. But what about a 10 speed fan? what do you call all of those speeds? They all have to be programed in somehow to the plugin.

So that's why I have limited the number of speeds.

Again, I'm sorry about that.
