### ISSUE TITLE
fan.set_speed is deprecated

### ISSUE THREAD

**Issue by gx1400** [finity69x2/fan-control-entity-row#56]
use fan.set_percentage
https://www.home-assistant.io/integrations/fan/

**Comment by SkilledAlpaca** [comment]
Using the `dev` version branch worked for me. 
https://github.com/finity69x2/fan-control-entity-row/blob/dev/dist/fan-control-entity-row.js

I may open another issue, but can we get a config to change the order or the buttons? I'm used to `Off` being on the left and `High` being on the right.

**Comment by finity69x2** [comment]
Yes, it is deprecated. That's why you need to use a different plugin as it says in the readme.

use fan-percent-button-row from my repo here instead


also when you use the other (or even this one) you can reverse the order of the buttons already. see the readme.

**Comment by SkilledAlpaca** [comment]
Apologies, but where does it link to "working" plugins? It just says if your fans are updated use `fan-percent-button-row` or `fan-mode-button-row` but doesn't say how to where to get those working. I stumbled upon the dev branch that fixed my issue but if I need to use something else I will.

**Comment by finity69x2** [comment]
If you are in the current repo then just click on my user at the top left and from there it will list all the repository in my account. They will be listed there. 

Sorry replying on my phone so it's hard to provide links 

I don't remember putting in a fix for this in the dev branch tho. So that's interesting.
